"""Migración inicial

Revision ID: a2034c84ad02
Revises: 
Create Date: 2024-11-15 15:02:19.409746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2034c84ad02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('divisas',
    sa.Column('id_divisa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_divisa', sa.String(length=50), nullable=False),
    sa.Column('simbolo', sa.String(length=10), nullable=True),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id_divisa')
    )
    op.create_table('promocion',
    sa.Column('id_promocion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_promocion', sa.String(length=100), nullable=False),
    sa.Column('tipo_descuento', sa.Enum('Porcentaje', 'Fijo'), nullable=False),
    sa.Column('valor_descuento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_promocion')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=100), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('nombre_rol', sa.Enum('ADMINISTRADOR', 'CLIENTE', 'VENDEDOR', name='rolenum'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id_carrito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    op.create_table('factura',
    sa.Column('id_factura', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_factura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('id_divisa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_divisa'], ['divisas.id_divisa'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_table('juegos',
    sa.Column('id_juego', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_juego', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('condicion', sa.Enum('Nuevo', 'Usado'), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_juego')
    )
    op.create_table('logs',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('detalle_factura',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_juego', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id_factura'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_juego'], ['juegos.id_juego'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_factura', 'id_juego')
    )
    op.create_table('resena',
    sa.Column('id_resena', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_juego', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_resena', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_juego'], ['juegos.id_juego'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_resena')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resena')
    op.drop_table('detalle_factura')
    op.drop_table('logs')
    op.drop_table('juegos')
    op.drop_table('factura')
    op.drop_table('carrito')
    op.drop_table('usuario')
    op.drop_table('promocion')
    op.drop_table('divisas')
    op.drop_table('categoria')
    # ### end Alembic commands ###
